version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: test_requirements.txt
          pkg-manager: pip
          pypi-cache: false

      - run:
          name: Run Tests
          command: |
            export CONFIG_FILE=${CIRCLE_WORKING_DIRECTORY}/config-sample.cfg
            echo $CONFIG_FILE
            pwd
            ls -l
            ls -l ${CIRCLE_WORKING_DIRECTORY}
            coverage run -m pytest --junitxml=test-results/test-results.xml

      - run:
          name: Generate reports
          command: |
            coverage report
            coverage xml -o test-results/coverage.xml
            coverage html
            ls -l

      - store_artifacts:
          path: test-results/coverage.xml

workflows:
  main:
    jobs:
      - build

