name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set variables
      run: |
        echo ::set-env name=IMAGE_NAME::"bee-api"
        echo ::set-env name=REPOSITORY::"erikdeirdre"
        echo ::set-env name=DOCKER_TAG::$(cat VERSION)

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$DOCKER_TAG
      
    - name: Push image to Docker Repo
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: $REPOSITORY/$IMAGE_NAME
        tags: $DOCKER_TAG
