name: merge-job

on:
  pull_request:
    types: [closed]

jobs:
  merge-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Increment Version if same as Master
      run: |
        echo ::set-env name=VERSION_CHANGE::0
        DIFF=$(git diff origin/$GITHUB_HEAD_REF origin/master  -- VERSION)
        if [[ -z "$DIFF" ]]; then
          IFS='.'; read -r -a array <<< "$(cat VERSION)"
          CNT="${array[1]}"
          ((CNT++))
          echo "${array[0]}.${CNT}.${array[2]}" >VERSION
          echo ::set-env name=VERSION_CHANGE::1
        fi

    - name: Commit Updated Version File
      if: env.VERSION_CHANGE == 1
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --local user.name ${GITHUB_ACTOR}
        git add VERSION
        git commit -m "Updated VERSION file"
  
    - name: Push changes to master
      if: env.VERSION_CHANGE == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true

    - name: Notify Helm Chart Repo of the Commit
      run: |
        API_VERSION=$(cat VERSION)
        curl -X POST https://api.github.com/repos/BeeRaspberry/helm-charts/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Content-Type: application/json' \
        -u ${{ secrets.ACCESS_TOKEN_REPO }} \
        --data '{"event_type": "version_change", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "version": "'${API_VERSION}'" }}'
